TeachLearnWeb/Controllers/ChatController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using System.Web.Mvc;
using TeachLearnWeb.Business;
using TeachLearnWeb.Data.POCOs.TeachLearnWeb;
using TeachLearnWeb.FormData.ChatController;

namespace TeachLearnWeb.Controllers
{
    public class ChatController : BaseController
    {
        IRepository<Conversation> _conversationRepository = _uow.GetRepository<Conversation>();
        IRepository<Message> _messageRepository = _uow.GetRepository<Message>();

        public ActionResult AddConversation()
        {
            return View();
        }

        [HttpPost]
        public ActionResult AddConversation(Conversation _conversation)
        {
            return View();
        }

        [HttpPost]
        public ActionResult SeeConversation()
        {
            return View();
        }

        [HttpPost]
        public ActionResult DeleteConversation()
        {
            return View();
        }

        public ActionResult AddMessage()
        {
            return View();
        }

        [HttpPost]
        public ActionResult AddMessage(Message _Message)
        {
            return View();
        }

        [HttpPost]
        public ActionResult SeeMessage()
        {
            return View();
        }

        [HttpPost]
        public ActionResult DeleteMessage()
        {
            return View();
        }

        [HttpPost]
        public ActionResult FavMessage()
        {
            return View();
        }



        public ActionResult Deneme()
        {
            return View();
        }

        [HttpGet]
        public async Task<PartialViewResult> ChatPanel(int userID)
        {
            IRepository<User> _userRepository = _uow.GetRepository<User>();
            User receiverUser;

            receiverUser = await _userRepository.SingleGetByAsync(w => w.ID == userID);

            Student currentStudent = HttpContext.Session["Student"] as Student;
            User senderUser = currentStudent.User;

            var a= Convert.ToBase64String(senderUser.ProfilePhoto);
            var b = Convert.ToBase64String(receiverUser.ProfilePhoto);
            
            Conversation conversation = conversation = await _conversationRepository.SingleGetByAsync(w => w.Participants.Select(S => S.ID).Contains(receiverUser.ID) && w.Participants.Select(s => s.ID).Contains(senderUser.ID) && w.Participants.Count == 2); ;

            List<Message> Messages = conversation == null ? new List<Message>():conversation.Messages.OrderByDescending(O=>O.SendTime).Take(15).ToList();


            return PartialView(new ChatFormData
            {
                SenderUsername = senderUser.Username,
                ReceiverUsername = receiverUser.Username,
                SenderConnectionID = senderUser.SignalRConnectionID,
                ReceiverConnectionID = receiverUser.SignalRConnectionID,
                SenderNameSurname = currentStudent.NameSurname,
                ReceiverNameSurname = receiverUser.Student.NameSurname,
                SenderPPBase64 = "data:image/png;base64," + Convert.ToBase64String(senderUser.ProfilePhoto),
                ReceiverPPBase64 = "data:image/png;base64," + Convert.ToBase64String(receiverUser.ProfilePhoto),
                Messages = Messages
            });
        }

        public PartialViewResult FriendsPanelPartial()
        {
            return PartialView("FriendsPanelPartial", GetOnlineFriends());
        }

        public IEnumerable<User> GetOnlineFriends()
        {
            var list= (HttpContext.Session["Student"] as Student)
                .User.Friends.Where(w => w.IsOnline == true);

            List<User> OnlineFriends = new List<User>();

            foreach(var item in list)
            {
                OnlineFriends.Add(item);
            }

            return OnlineFriends.AsEnumerable();

        }
    }
}

TeachLearnWeb/Controllers/UserController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using System.Web.Mvc;
using TeachLearnWeb.Business;
using TeachLearnWeb.Data.POCOs.TeachLearnWeb;
using TeachLearnWeb.FormData;
using TeachLearnWeb.ModelBinders;
using TeachLearnWeb.Security;
using System.Web.Security;
using TeachLearnWeb.Filters;
using TeachLearnWeb.FormData.UserController;
using TeachLearnWeb.FormData.UserController.Profile;
using System.Net;
using TeachLearnWeb.FormData.UserProfilePhoto;

namespace TeachLearnWeb.Controllers
{
    public class UserController : BaseController
    {
        IRepository<Student> _studentRepository = _uow.GetRepository<Student>();
        IRepository<User> _userRepository = _uow.GetRepository<User>();
        IRepository<FriendRelationship> _relationshipRepository = _uow.GetRepository<FriendRelationship>();
        IRepository<FriendRequest> _friendRequestRepository = _uow.GetRepository<FriendRequest>();
        [AllowAnonymous]
        public ActionResult CreateAccount()
        {
            return View(new AccountFormData());
        }

        [HttpPost]
        public async Task<ActionResult> CreateAccount([ModelBinder(typeof(CreateAccountModelBinder))] object[] dataArray)
        {
            if (ModelState.IsValid)
            {
                var _user = dataArray[0] as User;
                var _student = dataArray[1] as Student;


                //_user.FriendsParent = _user;
                //_user.FriendParentID = _user.ID;
                //await _userRepository.AddAsync(_user);

                //FriendRelationship newRelationship = new FriendRelationship();
                //newRelationship.Friend = _user;
                //newRelationship.FriendID = _user.ID;

                //await _relationshipRepository.AddAsync(newRelationship);

                try
                {
                    await _userRepository.AddAsync(_user);
                    await _studentRepository.AddAsync(_student);
                    await _uow.SaveChanges();

                }
                catch (Exception ex)
                {
                    while (ex.InnerException != null) ex = ex.InnerException;
                    ViewBag.Messsage = ex.Message;
                    ViewBag.Info = "danger";
                }
            }
            else
            {
                ViewBag.Message = "Please check again the fields!";
                ViewBag.Info = "danger";
            }
            return View();
        }

        [HttpPost]
        public async Task<JsonResult> Login(FormData.LoginFormData _loginCrediental)
        {
            var _userEnteredUsername = _loginCrediental.Username;
            var _userEnteredPassword = _loginCrediental.Password;

            if (await HashSaltClass.CheckCreedientals(_userEnteredUsername, _userEnteredPassword))
            {
                Student _loggedStudent = (await _userRepository.SingleGetByAsync(w => w.Username == _userEnteredUsername)).Student;
                _loggedStudent.User.IsOnline = true;
                Session["Student"] = _loggedStudent;
            }
            else //No account in db
            {
                TempData["Script"] = "alert('Login failed!');";
            }

            return Json("");
        }

        [UserAuthorizationFilter]
        [HttpPost]
        public async Task<ActionResult> LogOut()
        {
            (Session["Student"] as Student).User.IsOnline = false;
            await _uow.SaveChanges();
            FormsAuthentication.SignOut();
            Session.Abandon();

            return RedirectToAction("Index", "Home");
        }

        [UserAuthorizationFilter]
        public async Task<ActionResult> UserProfile(int? ID)
        {
            Student currentStudent = (ID == null ? Session["Student"] as Student : await _studentRepository.GetByIdAsync((int)ID));

            User currentUser = currentStudent.User;

            UserProfileFormData upfd = new UserProfileFormData();
            upfd.Username = currentUser.Username;
            upfd.NameSurname = currentStudent.NameSurname;
            upfd.ConnectionCount = currentUser.ConnectionsAsSharer.Count + currentUser.ConnectionsAsViewer.Count;

            upfd.ParameteredUserID = ID == null ? null : ID;

            if (ID != null)
            {
                if ((Session["Student"] as Student).User.SentFriendRequests.Any(w => w.RequestToID == currentUser.ID && w.IsAccepted == false))
                {
                    upfd.IsSentRequest = true;
                }
                else
                {
                    if ((Session["Student"] as Student).User.Friends.Contains(currentUser) && currentUser.Friends.Contains((Session["Student"] as Student).User))
                    {
                        upfd.IsFriend = true;
                    }
                }
            }


            #region EDUCATION
            if (currentStudent.Educations.Count != 0)
            {
                UserProfileEducationFormData upefd = new UserProfileEducationFormData();

                foreach (var education in currentStudent.Educations)
                {
                    upefd.EducationID = education.ID;

                    UserProfileEducationUniversityFormData upeufd = upefd.Universities.SingleOrDefault(w => w.UniversityName == education.University.Name);

                    if (upeufd != null) //university varsa
                    {
                        UserProfileEducationFacultyFormData upeffd = upeufd.Faculties.SingleOrDefault(w => w.FacultyName == education.Faculty.Name);

                        if (upeffd != null)//faculty varsa
                        {
                            UserProfileEducationDepartmentFormData upedfd = upeffd.Departments.SingleOrDefault(w => w.DepartmentName == education.Department.Name);

                            if (upedfd != null)//department varsa
                            {
                                upedfd.LessonCount = education.Scores.Count;
                                upeffd.LessonCount = education.Scores.Count;
                                upeufd.LessonCount = education.Scores.Count;

                                foreach (var score in education.Scores)
                                {
                                    foreach (var note in score.Notes)
                                    {
                                        upedfd.AverageGrade += ((note.ResultPoint * note.Effect) / 100);
                                    }
                                }
                            }
                            else
                            {
                                upedfd = new UserProfileEducationDepartmentFormData();
                                upedfd.DepartmentName = education.Department.Name;
                                upedfd.Term = education.Period.Semester;
                                upedfd.Year = education.Period.Year;

                                upedfd.LessonCount = education.Scores.Count;
                                upeffd.LessonCount = education.Scores.Count;
                                upeufd.LessonCount = education.Scores.Count;

                                foreach (var score in education.Scores)
                                {
                                    foreach (var note in score.Notes)
                                    {
                                        upedfd.AverageGrade += ((note.ResultPoint * note.Effect) / 100);
                                    }
                                }

                                upeffd.Departments.Add(upedfd);
                            }
                        }
                        else
                        {
                            upeffd = new UserProfileEducationFacultyFormData();
                            upeffd.FacultyName = education.Faculty.Name;

                            upeufd.Faculties.Add(upeffd);

                            UserProfileEducationDepartmentFormData upedfd = upeffd.Departments.SingleOrDefault(w => w.DepartmentName == education.Department.Name);

                            if (upedfd != null)//department varsa
                            {
                                upedfd.LessonCount = education.Scores.Count;
                                upeffd.LessonCount = education.Scores.Count;
                                upeufd.LessonCount = education.Scores.Count;

                                foreach (var score in education.Scores)
                                {
                                    foreach (var note in score.Notes)
                                    {
                                        upedfd.AverageGrade += ((note.ResultPoint * note.Effect) / 100);
                                    }
                                }


                            }
                            else
                            {
                                upedfd = new UserProfileEducationDepartmentFormData();
                                upedfd.DepartmentName = education.Department.Name;
                                upedfd.Term = education.Period.Semester;
                                upedfd.Year = education.Period.Year;


                                upedfd.LessonCount = education.Scores.Count;
                                upeffd.LessonCount = education.Scores.Count;
                                upeufd.LessonCount = education.Scores.Count;

                                foreach (var score in education.Scores)
                                {
                                    foreach (var note in score.Notes)
                                    {
                                        upedfd.AverageGrade += ((note.ResultPoint * note.Effect) / 100);
                                    }
                                }

                                upeffd.Departments.Add(upedfd);
                            }

TeachLearnWeb/Views/Shared/_Grid.cshtml
@using GridMvc.Columns
@model GridMvc.IGrid
@if (Model == null) { return; }
@if (Model.RenderOptions.RenderRowsOnly)
{
    @RenderGridBody();
}
else
{
    <div class="grid-mvc" data-lang="@Model.Language" data-gridname="@Model.RenderOptions.GridName" data-selectable="@Model.RenderOptions.Selectable.ToString().ToLower()" data-multiplefilters ="@Model.RenderOptions.AllowMultipleFilters.ToString().ToLower()">
        <div class="grid-wrap">
            <table class="table table-striped grid-table">
                @* Draw grid header *@
                <thead>
                    @RenderGridHeader()
                </thead>
                <tbody>
                    @RenderGridBody()
                </tbody>
            </table>
            @RenderGridPager()
        </div>
    </div>
}
@helper RenderGridBody()
{
    if (!Model.ItemsToDisplay.Any())
    {
    <tr class="grid-empty-text">
        <td colspan="@Model.Columns.Count()">
            @Model.EmptyGridText
        </td>
    </tr>
    }
    else
    {
        foreach (object item in Model.ItemsToDisplay)
        {
    <tr class="grid-row @Model.GetRowCssClasses(item)">
        @foreach (IGridColumn column in Model.Columns)
        {
            @column.CellRenderer.Render(column, column.GetCell(item))
        }
    </tr>
        }
    }
}
@helper RenderGridHeader()
{
    <tr>
        @foreach (IGridColumn column in Model.Columns)
        {
            @column.HeaderRenderer.Render(column)
        }
    </tr>
}
@helper RenderGridPager()
{
    if (Model.EnablePaging && Model.Pager != null)
    {
    <div class="grid-footer">
        @Html.Partial(Model.Pager.TemplateName, Model.Pager)
    </div>
    }
}

TeachLearnWeb/Views/Shared/_GridPager.cshtml
@model GridMvc.Pagination.GridPager
@if (Model == null || Model.PageCount <= 1)
{
    return;
}
<div class="grid-pager">
    <ul class="pagination">
        @if (Model.CurrentPage > 1)
        {
            <li>
                <a href="@Model.GetLinkForPage(Model.CurrentPage - 1)">«</a>
            </li>
        }

        @if (Model.StartDisplayedPage > 1)
        {
            <li>
                <a href="@Model.GetLinkForPage(1)">1</a>
            </li>
            if (Model.StartDisplayedPage > 2)
            {
            <li><a href="@Model.GetLinkForPage(Model.StartDisplayedPage - 1)">...</a></li>
            }
        }
        @for (int i = Model.StartDisplayedPage; i <= Model.EndDisplayedPage; i++)
        {
            if (i == Model.CurrentPage)
            {
            <li class="active"><span>@i</span></li>
            }
            else
            {
            <li><a href="@Model.GetLinkForPage(i)">@i</a></li>
            }
        }
        @if (Model.EndDisplayedPage < Model.PageCount)
        {
            if (Model.EndDisplayedPage < Model.PageCount - 1)
            {
            <li><a href="@Model.GetLinkForPage(Model.EndDisplayedPage + 1)">...</a></li>
            }
            <li><a href="@Model.GetLinkForPage(Model.PageCount)">@Model.PageCount</a></li>
        }
        @if (Model.CurrentPage < Model.PageCount)
        {
            <li><a href="@Model.GetLinkForPage(Model.CurrentPage + 1)">»</a></li>
        }
    </ul>
</div>

TeachLearnWeb/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>@ViewBag.Title - LiveCampus</title>
    <script src="~/Scripts/jquery-3.3.1.min.js"></script>
    <script src="~/Scripts/jquery.unobtrusive-ajax.min.js"></script>
    <link rel="stylesheet" type="text/css" href="http://www.shieldui.com/shared/components/latest/css/light-bootstrap/all.min.css" />
    <script type="text/javascript" src="http://www.shieldui.com/shared/components/latest/js/shieldui-all.min.js"></script>
    @Styles.Render("~/Content/css")
    @*@Scripts.Render("~/bundles/modernizr")*@

</head>
<body>
    <nav class="navbar navbar-default navbar-fixed-top">
        <div class="container">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                <a href="@Url.Action("Index", "Home")"><img src="~/images/LiveCampusLogoTransaparan.png" width="80" height="60" /></a>
            </div>
            <div class="navbar-collapse">
                <ul class="nav navbar-nav">
                    <li>@Html.ActionLink("Home", "Index", "Home")</li>
                    
                    @if (Session["Student"] != null)
                    {
                        <li>@Html.ActionLink("List Educations", "ListEducations", "Student")</li>
                        <li>@Ajax.ActionLink("Connect as Sharer", "ConnectAsSharer", "Connection", new AjaxOptions { HttpMethod = "POST", OnSuccess = "alert('Please open your winform application!');" })</li>
                        <li>@Ajax.ActionLink("Connect as Viewer", "ConnectAsViewer", "Connection", new AjaxOptions { HttpMethod = "POST", OnSuccess = "alert('Please open your winform application!');" })</li>


                        if ((Session["Student"] as TeachLearnWeb.Data.POCOs.TeachLearnWeb.Student).User.IsAdmin)
                        {
                            <li>@Html.ActionLink("Admin Page", "Index", "Admin")</li>
                        }

                    }
                    <li>@Html.ActionLink("Forum", "Index", "Forum")</li>
                    <li>@Html.ActionLink("About", "About", "Home")</li>
                    <li>@Html.ActionLink("Contact Us", "Contact", "Home")</li>
                    <li>@Html.ActionLink("Grade Competition", "GradeCompetition", "Student")</li>
                </ul>

                <ul class="nav navbar-nav navbar-right">
                    <li><input id="autocomplete1" type="text" placeholder="Type a username" class="form-control" style="margin-bottom:-30px;display:inline-block" /></li>
                    <li><div class="btn btn-danger form-control" id="btnSearchUser" style="margin-bottom:-30px;display:inline-block">Search</div></li>

                    @Html.Partial("_LgnPartial")
                </ul>
            </div>
        </div>
    </nav>
    <div class="container body-content">
        <br />
        <br />
        <br />
        @RenderBody()
        <hr />
        <footer>
            <div style="float:right">
                @if (Session["Student"] != null)
                {
                    @Html.Action("FriendsPanelPartial", "Chat")
                    //@Html.Partial("../Chat/FriendsPanelPartial")
                }
            </div>
            <p>&copy; @DateTime.Now.Year - LiveCampus</p>
        </footer>
    </div>

    @Scripts.Render("~/bundles/bootstrap")
    @RenderSection("scripts", required: false)
</body>
</html>



<script type="text/javascript">
    $(function () {
        var usernames;

        $.when($.ajax({
            method: "POST",
            url: '@Url.Action("GetAllUsernames","User")',
            success: function (usernameList) {
                usernames = usernameList;
            }
        })).done(function () {

            $("#autocomplete1").shieldAutoComplete({
                dataSource: {
                    data: usernames
                },
                minLength: 1
            });
        });

        $('#btnSearchUser').click(function () {

            var username = $('#autocomplete1').val();
            var userID;
            $.ajax({
                method: "POST",
                url: '@Url.Action("GetIDByUsername","User")',
                data:{username:username},
                success: function (ID) {
                    userID = ID;
                    var link='@Url.Action("UserProfile","User",new { ID=0})';
                    link=link.replace("/0","/"+userID);
                    window.location.href = link;
                }
            });
        });

    });

</script>

TeachLearnWeb/Views/Shared/_LgnPartial.cshtml
@{
    if (Session["Student"] == null)
    {
        <li class="dropdown">
            <a href="#" class="dropdown-toggle" data-toggle="dropdown"><b>Login</b> <span class="caret"></span></a>
            <ul id="login-dp" class="dropdown-menu" style="width:220px">
                <li>
                    <div class="row">
                        <div class="col-md-12">
                            @using (Ajax.BeginForm("Login", "User",null, new AjaxOptions { HttpMethod = "POST", OnSuccess = "window.location.reload();" }, new { htmlAttributes = new { @class = "form" }, id = "login-nav" }))
                            {
                                @Html.AntiForgeryToken()
                                <div class="form-group">
                                    <label class="sr-only" for="exampleInputEmail2">Username</label>
                                    <input type="text" class="form-control" id="Username" name="Username" placeholder="Username or E-mail" style="width:200px; margin:0px 0px 0px 10px;" required>
                                </div>
                                <div class="form-group">
                                    <label class="sr-only" for="exampleInputPassword2">Password</label>
                                    <input type="password" class="form-control" id="Password" name="Password" placeholder="Password" style="width:200px; margin:0px 0px 0px 10px" required>
                                </div>
                                <div class="form-group">
                                    <button type="submit" id="btnLogin" class="btn btn-primary btn-block" style="width:200px; margin:0px 0px 0px 10px">Login</button>
                                </div>
                                <div class="form-group">
                                    <a href="@Url.Action("CreateAccount","User")" style="font-size:12px; margin:0px auto 0px 42px">Does not have account?</a>
                                </div>
                                <script type="text/javascript">@ViewBag.Script</script>
                            }
                        </div>
                    </div>
                </li>
            </ul>
        </li>
    }
    else
    {
        var student = (TeachLearnWeb.Data.POCOs.TeachLearnWeb.Student)HttpContext.Current.Session["Student"];
        <li class="dropdown">
            <a href="#" class="dropdown-toggle" data-toggle="dropdown"><b>Welcome @student.NameSurname</b> <span class="caret"></span></a>
            <ul id="login-dp" class="dropdown-menu" style="width:100px">
                <li>
                    <div class="row">
                        <div class="col-md-12">
                            @using (Html.BeginForm("UserProfile", "User", FormMethod.Post, new { htmlAttributes = new { @class = "form" } }))
                            {
                                <div class="form-group">
                                    <button id="btnProfile" class="btn btn-primary" style="width:130px; margin:0px 10px 0px 10px">Profile</button>
                                </div>
                            }

                            @using (Html.BeginForm("Logout", "User", FormMethod.Post, new { htmlAttributes = new { @class = "form" } }))
                            {
                                <div class="form-group">
                                    <button type="submit" class="btn btn-danger btn-block" style="width:130px; margin:0px 10px 0px 10px">Logout</button>@*Buraya log off controller yolu ekle!!!!*@
                                </div>
                            }
                        </div>
                    </div>
                </li>

            </ul>
        </li>
    }
}