TeachLearnWeb/Controllers/ConnectionController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Net;
using System.Threading.Tasks;
using System.Web.Mvc;
using TeachLearnWeb.Business;
using TeachLearnWeb.Data.POCOs.TeachLearnWeb;
using TeachLearnWeb.Filters;
using TeachLearnWeb.FormData.ConnectionController;
using TeachLearnWeb.FormData.UserProfilePhoto;

namespace TeachLearnWeb.Controllers
{
    [UserAuthorizationFilter]
    public class ConnectionController : BaseController
    {
        IRepository<Connection> connectionRepository = _uow.GetRepository<Connection>();
        IRepository<User> userRepository = _uow.GetRepository<User>();
        IRepository<Review> reviewRepository = _uow.GetRepository<Review>();
        IRepository<ScreenShareRequest> screenShareRequestRepository = _uow.GetRepository<ScreenShareRequest>();

        [HttpPost]
        public async Task<ActionResult> ConnectAsSharer()
        {
            int userID = (Session["Student"] as Student).ID;
            User sharerUser = await userRepository.SingleGetByAsync(w => w.ID == userID);


            if (sharerUser.ConnectionsAsViewer.Where(w => w.IsConnectionEnded == false && w.IsConnectionStarted == false).Count() != 0)
            {
                sharerUser.ConnectionsAsViewer.Where(w => w.IsConnectionEnded == false && w.IsConnectionStarted == false).ToList().ForEach(each => each.IsConnectionEnded = true);
            }


            sharerUser.PendingStatus = "Sharer";

            await _uow.SaveChanges();

            return new HttpStatusCodeResult(HttpStatusCode.OK);
        }

        [HttpPost]
        public async Task<ActionResult> ConnectAsViewer()
        {
            int userID = (Session["Student"] as Student).ID;
            User sharerUser = await userRepository.SingleGetByAsync(w => w.ID == userID);


            if (sharerUser.ConnectionsAsSharer.Where(w => w.IsConnectionEnded == false && w.IsConnectionStarted == false).Count() != 0)
            {
                sharerUser.ConnectionsAsSharer.Where(w => w.IsConnectionEnded == false && w.IsConnectionStarted == false).ToList().ForEach(each => each.IsConnectionEnded = true);

            }

            sharerUser.PendingStatus = "Viewer";

            await _uow.SaveChanges();

            return new HttpStatusCodeResult(HttpStatusCode.OK);
        }

        public ActionResult PreviousConnections()
        {
            if (Session["Student"] != null)
            {
                User currentUser = (Session["Student"] as Student).User;

                List<Connection> Connections = new List<Connection>();
                Connections.AddRange(currentUser.ConnectionsAsSharer);
                Connections.AddRange(currentUser.ConnectionsAsViewer);

                return View(Connections);
            }
            else
            {
                return View();
            }
        }

        public async Task<ActionResult> ConnectionDetails(int ID)
        {

            Connection conn = await connectionRepository.GetByIdAsync(ID);

            if ((Session["Student"] as Student).User.ID == conn.SharerID || (Session["Student"] as Student).User.ID == conn.ViewerID)
            {
                TempData["Unauthorized"] = true;
            }
                ConnectionDetailsFormData cdfd = new ConnectionDetailsFormData();
                cdfd.Connection = conn;





                foreach (var review in cdfd.Connection.Reviews)
                {
                    ProfilePhotoFormData ppfd = new ProfilePhotoFormData();

                    ppfd.ID = review.Sender.ID;
                    ppfd.Base64Image = "data:image/png;base64," + Convert.ToBase64String(review.Sender.ProfilePhoto);


                    cdfd.ProfilePhotoFormDatas.Add(ppfd);

                }

                return View(cdfd);
            

        }

        public async Task<PartialViewResult> EditConnectionNamePartial(int ID)
        {
            Connection connection = await connectionRepository.GetByIdAsync(ID);

            TempData["ConnectionName"] = connection.ConnectionName;
            TempData["ConnectionID"] = connection.ID;
            return PartialView();
        }

        [HttpPost]
        public async Task<ActionResult> UpdateConnectionName(int ID, string name)
        {
            Connection connection = await connectionRepository.GetByIdAsync(ID);

            connection.ConnectionName = name;

            await _uow.SaveChanges();


            return new HttpStatusCodeResult(HttpStatusCode.OK);
        }


        public async Task<ActionResult> CreateReview(int ID)
        {
            Connection connection = await connectionRepository.GetByIdAsync(ID);

            return View(connection);
        }

        [HttpPost]
        public async Task<ActionResult> CreateReview(int ID, string review, string Vote = "upvote")
        {
            Connection currentConnection = await connectionRepository.GetByIdAsync(ID);
            await connectionRepository.AttachAsync(currentConnection);

            Review newReview = new Review();
            newReview.Connection = currentConnection;
            newReview.Message = review;
            newReview.Sender = (Session["Student"] as Student).User;

            if (Vote == "downvote")
            {
                newReview.Vote = Data.POCOs.TeachLearnWeb.Vote.DownVote;
            }
            else
                newReview.Vote = Data.POCOs.TeachLearnWeb.Vote.Upvote;

            currentConnection.Reviews.Add(newReview);

            await reviewRepository.AddAsync(newReview);

            try
            {
                await _uow.SaveChanges();
            }
            catch (Exception ex)
            {

            }
            return new HttpStatusCodeResult(HttpStatusCode.OK);
        }

        [HttpPost]
        public async Task<ActionResult> EstablishPreviousConnection(int ID, string status)
        {
            User currentUser = (Session["Student"] as Student).User;
            //currentUser.PendingStatus = "Sharer";
            if (!currentUser.SentScreenShareRequests.Where(w => w.IsAccepted == false && w.NewConnection.IsConnectionEnded == false).Any())
            {
                Connection conn = await connectionRepository.GetByIdAsync(ID);

                User partnerUser = conn.ViewerID == currentUser.ID ? conn.Sharer : conn.Viewer;

                ScreenShareRequest ssRequest = new ScreenShareRequest();
                ssRequest.Requester = currentUser;
                ssRequest.RequestTo = partnerUser;

                currentUser.SentScreenShareRequests.Add(ssRequest);
                partnerUser.ReceivedScreenShareRequests.Add(ssRequest);

                ssRequest.RequesterRequestType = status == "Sharer" ? RequestType.Sharer : RequestType.Viewer;

                ssRequest.RequestToRequestType = ssRequest.RequesterRequestType == RequestType.Sharer ? RequestType.Viewer : RequestType.Sharer;

                ssRequest.NewConnection = conn;

                //Connection newConnection = new Connection();
                //newConnection.ConnectionName = conn.ConnectionName.Contains("Repeat") ? conn.ConnectionName : conn.ConnectionName + " (Repeat)";
                //newConnection.ForumDepartmentCategory = conn.ForumDepartmentCategory;
                //newConnection.ConnectionDate = DateTime.Now;

                //conn.ForumDepartmentCategory.Connections.Add(newConnection);

                //if (status == "Sharer")
                //{
                //    currentUser.PendingStatus = "Sharer";
                //    newConnection.Sharer = currentUser;
                //    currentUser.ConnectionsAsSharer.Add(newConnection);
                //}
                //else
                //{
                //    currentUser.PendingStatus = "Viewer";
                //    newConnection.Viewer = currentUser;
                //    currentUser.ConnectionsAsViewer.Add(newConnection);
                //}

                //ssRequest.RequestedConnection = conn;
                //conn.BaseRequests.Add(ssRequest);

                //ssRequest.NewConnection = newConnection;
                //newConnection.BaseRequests.Add(ssRequest);

                await screenShareRequestRepository.AddAsync(ssRequest);
                //await connectionRepository.AddAsync(newConnection);

                try
                {
                    await _uow.SaveChanges();
                }
                catch (Exception ex) { }
                return new HttpStatusCodeResult(HttpStatusCode.OK);
            }

            else
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest, "You already have an existing connection pending!");


        }

        public ActionResult PendingConnection()
        {
            Connection pendingConnection = (Session["Student"] as Student).User.ConnectionsAsSharer.SingleOrDefault(w => w.IsConnectionEnded == false);
            pendingConnection = pendingConnection == null ? (Session["Student"] as Student).User.ConnectionsAsViewer.SingleOrDefault(w => w.IsConnectionEnded == false) : pendingConnection;


            return View(pendingConnection);
        }

        [HttpPost]
        public async Task<ActionResult> DeletePendingConnection(int ID)
        {
            Connection connection = await connectionRepository.GetByIdAsync(ID);

            await connectionRepository.DeleteAsync(connection);

            await _uow.SaveChanges();

            return new HttpStatusCodeResult(HttpStatusCode.OK);
        }

        public async Task<ActionResult> EditReview(int ID)
        {
            Review editedReview = await reviewRepository.GetByIdAsync(ID);

            return View(editedReview);
        }

        [HttpPost]
        public async Task<ActionResult> EditReview(int ID, string review, string Vote = "upvote")
        {
            Review editedReview = await reviewRepository.GetByIdAsync(ID);
            editedReview.Message = review;

            if (Vote == "downvote")

TeachLearnWeb/Views/Connection/ConnectionDetails.cshtml
@model TeachLearnWeb.FormData.ConnectionController.ConnectionDetailsFormData

@{
    ViewBag.Title = "ConnectionDetails";
    Layout = "~/Views/Shared/_Layout.cshtml";
    int currentUserID = (Session["Student"] as TeachLearnWeb.Data.POCOs.TeachLearnWeb.Student).User.ID;
}
@*<script src="~/Scripts/jquery-3.3.1.min.js"></script>
    <script src="~/Scripts/jquery.unobtrusive-ajax.min.js"></script>*@
<link href="~/Content/ReviewStyle.css" rel="stylesheet" />
<div id="ConnectionNameArea"><h2>@Model.Connection.ConnectionName</h2></div>

<div>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.Connection.ConnectionName)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Connection.ConnectionName)
        </dd>

        <dt>
            Sharer
        </dt>
        <dd>
            @Html.DisplayFor(model => model.Connection.Sharer.Username)
        </dd>

        <dt>
            Viewer
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Connection.Viewer.Username)
        </dd>




        @*<dt>
                ConnectionString
            </dt>

            <dd>
                @Html.DisplayFor(model => model.ConnectionString)
            </dd>*@

        @*<dt>
                @Html.DisplayNameFor(model => model.ConnectionDate)
            </dt>

            <dd>
                @Html.DisplayFor(model => model.ConnectionDate)
            </dd>

            <dt>
                @Html.DisplayNameFor(model => model.ConnectionDuration)
            </dt>

            <dd>
                @Html.DisplayFor(model => model.ConnectionDuration)
            </dd>*@

    </dl>
</div>


<div class="dialogArea"></div>

@if (!Model.Connection.BaseRequests.Any())
{
    if (TempData["Unauthorized"] != null)
    {
    <p>
        @Ajax.ActionLink("Connect Again As Sharer", "EstablishPreviousConnection", new { ID = Model.Connection.ID, status = "Sharer" }, new AjaxOptions { HttpMethod = "POST", Confirm = "Are you sure you want to make this connection again as sharer? (Other user will be notified once the desktop application is opened!)", OnFailure = "alert('You already have an existing pending connection!');" }) |
        @Ajax.ActionLink("Connect Again As Viewer", "EstablishPreviousConnection", new { ID = Model.Connection.ID, status = "Viewer" }, new AjaxOptions { HttpMethod = "POST", Confirm = "Are you sure you want to make this connection again as sharer? (Other user will be notified once the desktop application is opened!)", OnFailure = "alert('You already have an existing pending connection!');" }) |
        @Ajax.ActionLink("Edit Connection Name", "EditConnectionNamePartial", new { ID = Model.Connection.ID }, new AjaxOptions { HttpMethod = "GET", InsertionMode = InsertionMode.Replace, UpdateTargetId = "ConnectionNameArea" })
        @*@Html.ActionLink("Edit", "Edit", new { id = Model.ID }) |
            @Html.ActionLink("Back to List", "Index")*@
    </p>
    }


    <div class="container">
        <div class="row">
            <h2>Reviews</h2>
            <hr style="border-color:red" />
        </div>
    </div>

    <div class="container">
        <div class="row">
            <div id="carousel-reviews" class="carousel slide" data-ride="carousel">
                <div class="carousel-inner">
                    <div class="item active">
                        @foreach (var review in Model.Connection.Reviews)
                        {
                            <div class="col-md-4 col-sm-6 hidden-xs">
                                <div class="block-text rel zmin">
                                    <a title="" href="@Url.Action("UserProfile", "User", new { ID = review.Sender.ID })">@review.Sender.Username</a>
                                    <div align="center">
                                        @if (review.Vote == TeachLearnWeb.Data.POCOs.TeachLearnWeb.Vote.Upvote)
                                        {
                                            <span class="glyphicon glyphicon-thumbs-up"></span>
                                        }
                                        @if (review.Vote == TeachLearnWeb.Data.POCOs.TeachLearnWeb.Vote.DownVote)
                                        {
                                            <span class="glyphicon glyphicon-thumbs-down"></span>
                                        }
                                    </div>
                                    <p>@review.Message</p>
                                    <ins class="ab zmin sprite sprite-i-triangle block"></ins>
                                </div>
                                <a href="@Url.Action("UserProfile","User",new { ID=review.UserID})">
                                    <div class="person-text rel">
                                        <img class="img-circle" src="@Model.ProfilePhotoFormDatas.FirstOrDefault(w => w.ID == review.Sender.ID).Base64Image" width="20%" height="auto" />
                                    </div>
                                </a>
                            </div>
                            if (review.Sender.ID == currentUserID)
                            {
                                @Html.ActionLink("Edit Review", "EditReview", new { ID = review.ID });
                            }
                        }
                    </div>
                </div>
            </div>

        </div>
    </div>
}

@if (Model.Connection.BaseRequests.Any() && TempData["Unauthorized"]!=null)
{
    <div>ALREADY SENT A REQUEST!</div>
}

TeachLearnWeb/Views/Connection/CreateReview.cshtml
@model TeachLearnWeb.Data.POCOs.TeachLearnWeb.Connection

@{
    ViewBag.Title = "CreateReview";
    Layout = "~/Views/Shared/_Layout.cshtml";
}





<br />
<br />
<br />
@Model.ConnectionName Reviews

<input type="hidden" value="@Model.ID" id="modelID"/>
<div class="input-group">

    <div class="col-xs-5">
        <input class="form-control" name="group100" type="radio" value="upvote" id="upvote">
        <span class="input-group-addon"><span class="glyphicon glyphicon-thumbs-up"></span></span>
        @*<label class="form-control" for="radio100" ><span class="glyphicon glyphicon-thumbs-up"></span></label>*@
    </div>
     
    <div class="col-xs-2"></div>

    <div class="col-xs-5">
        <input class="form-control" name="group100" type="radio" id="downvote" value="downvote" checked>
        <span class="input-group-addon"><span class="glyphicon glyphicon-thumbs-down"></span></span>
        @*<label class="form-control" for="radio101"><span class="glyphicon glyphicon-thumbs-down"></span></label>*@
    </div>
</div>




<div class="form-group">
    <label for="comment">REVIEW:</label>
    <textarea class="form-control" rows="8" id="reviewArea" style="resize:none;min-width:100%;"></textarea>
</div>

<div class="btn btn-danger" id="btnSendReview">SEND REVIEW</div>


<script>

    $(function () {
        $('#btnSendReview').click(function () {
            var ID = $('#modelID').val();
            var review=$('#reviewArea').val();
            var radioVote=$('input[name=group100]:checked').val();

            $.ajax({
                method: "POST",
                url: '@Url.Action("CreateReview","Connection")',
                data: { ID: ID, review: review,vote:radioVote },
                success: function () {
                    var link='@Url.Action("ConnectionDetails",new { ID=0})' ;
                    link=link.replace('/0','/'+ID);
                    window.location.href =link;
                }
            });
        });
    });



</script>

TeachLearnWeb/Views/Connection/EditConnectionNamePartial.cshtml
<br />
<br />
<br />
<input type="hidden" value="@TempData["ConnectionID"]" id="idArea" />
<input type="text" id="ConnectionName" placeholder="@TempData["ConnectionName"].ToString()"/>
<br />
<br />
<div class="btn btn-default" id="btnUpdate">Update</div>
<div class="btn btn-danger" id="btnCancel">Cancel</div>

<script>
    $(function () {
        $('#btnUpdate').click(function () {
            var connectionName=$('#ConnectionName').val();
            var ID=$('#idArea').val();

            $.ajax({
                method: "POST",
                url:'../UpdateConnectionName',
                type:'json',
                data: { ID: ID, name: connectionName },
                success: function () {
                    window.location.reload();
                }, error: function () {
                    window.location.reload();
                }

            });
        });

        $('#btnCancel').click(function () {
            window.location.reload();

        });

    });

</script>

TeachLearnWeb/Views/Connection/EditReview.cshtml
@model TeachLearnWeb.Data.POCOs.TeachLearnWeb.Review

@{
    ViewBag.Title = "EditReview";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h2>EditReview</h2>

<input type="hidden" value="@Model.ID" id="modelID" />
<input type="hidden" value="@Model.ConnectionID" id="modelConnID" />
<div class="input-group">

    <div class="col-xs-5">
        <input class="form-control" name="group100" type="radio" value="upvote" id="upvote">
        <span class="input-group-addon"><span class="glyphicon glyphicon-thumbs-up"></span></span>
    </div>

    <div class="col-xs-2"></div>

    <div class="col-xs-5">
        <input class="form-control" name="group100" type="radio" id="downvote" value="downvote" checked>
        <span class="input-group-addon"><span class="glyphicon glyphicon-thumbs-down"></span></span>
    </div>
</div>

<div class="form-group">
    <label for="comment">REVIEW:</label>
    <textarea class="form-control" rows="8" id="reviewArea" style="resize:none;min-width:100%;"></textarea>
</div>

<div class="btn btn-danger" id="btnSendReview">EDIT REVIEW</div>


<div>
    @Html.ActionLink("Back to Details", "ConnectionDetails",new { ID=Model.ConnectionID})
</div>


<script>

    $(function () {
        $('#btnSendReview').click(function () {
            var ID = $('#modelID').val();
            var connID = $('#modelConnID').val();
            var review=$('#reviewArea').val();
            var radioVote=$('input[name=group100]:checked').val();

            $.ajax({
                method: "POST",
                url: '@Url.Action("EditReview","Connection")',
                data: { ID: ID, review: review,vote:radioVote },
                success: function () {
                    var link = '@Url.Action("ConnectionDetails",new { ID=0})';
                    link = link.replace('/0', '/' + connID);
                    window.location.href = link;
                }
            });
        });
    });

</script>

TeachLearnWeb/Views/Connection/PendingConnection.cshtml
@model TeachLearnWeb.Data.POCOs.TeachLearnWeb.Connection

@{
    ViewBag.Title = "PendingConnection";
    Layout = "~/Views/Shared/_Layout.cshtml";

    string SharerName = "";
    string ViewerName = "";

    if (Model != null)
    {
        SharerName = Model.Sharer == null ? "" : Model.Sharer.Username;
        ViewerName = Model.Viewer == null ? "" : Model.Viewer.Username;
    }
}
<br />
<br />
<br />
@if (Model != null)
{
    <h2>PendingConnection</h2>

    <div>
        <h4>Connection</h4>
        <hr />
        <dl class="dl-horizontal">

            <dt>
                @Html.DisplayNameFor(model => model.ConnectionName)
            </dt>

            <dd>
                @Html.DisplayFor(model => model.ConnectionName)
            </dd>

            <dt>
                Sharer:
            </dt>

            <dd>
                @SharerName
            </dd>

            <dt>
                Viewer:
            </dt>

            <dd>
                @ViewerName
            </dd>

            <dt>
                @Html.DisplayNameFor(model => model.ConnectionDate)
            </dt>

            <dd>
                @Html.DisplayFor(model => model.ConnectionDate)
            </dd>

        </dl>
    </div>
    <p>
        @Ajax.ActionLink("Delete This Connection", "DeletePendingConnection", new { ID = Model.ID }, new AjaxOptions { HttpMethod = "POST", Confirm = "Are you sure you want to delete this pending connection?" }) |
        @Html.ActionLink("Back to List", "PreviousConnections")
    </p>
}
@if (Model == null)
{
    <h1>YOU DO NOT HAVE ANY PENDING CONNECTION!</h1>
}

TeachLearnWeb/Views/Connection/PreviousConnections.cshtml
@model IEnumerable<TeachLearnWeb.Data.POCOs.TeachLearnWeb.Connection>

@{
    ViewBag.Title = "PreviousConnections";
}

<h2>Previous Connections</h2>

@if (Model.Count()!=0)
{
<table class="table">
    <tr>
        <th>
            Viewer
        </th>
        <th>
            Sharer
        </th>
        <th>
            @Html.DisplayNameFor(model => model.ConnectionName)
        </th>
        <th>
            Reviews
        </th>
        <th></th>
    </tr>

@foreach (var item in Model)
{
    <tr>
        <td>
            @Html.DisplayFor(modelItem => item.Viewer.Username)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.Sharer.Username)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.ConnectionName)
        </td>
        <td>
            @item.Reviews.Count
        </td>
        <td>
            Connect again as :
            @Ajax.ActionLink("Connect Again As Sharer", "EstablishPreviousConnection", new { ID = item.ID, status = "Sharer" }, new AjaxOptions { HttpMethod = "POST", Confirm = "Are you sure you want to make this connection again as sharer? (Other user will be notified once the desktop application is opened!)", OnFailure = "alert('You already have an existing pending connection!');" }) |
            @Ajax.ActionLink("Connect Again As Viewer", "EstablishPreviousConnection", new { ID = item.ID, status = "Viewer" }, new AjaxOptions { HttpMethod = "POST", Confirm = "Are you sure you want to make this connection again as sharer? (Other user will be notified once the desktop application is opened!)", OnFailure = "alert('You already have an existing pending connection!');" }) |
        </td>
        <td>
            @Html.ActionLink("Add Review!","CreateReview",new { ID=item.ID})
        </td>
        <td>
            @Html.ActionLink("Details", "ConnectionDetails", new { ID = item.ID })
        </td>
    </tr>
}

</table>
}
@if (Model.Count() == 0)
{
    <h1>You have no previous connections!</h1>
}