TeachLearnWeb/Controllers/ForumController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Net;
using System.Threading;
using System.Threading.Tasks;
using System.Web.Mvc;
using TeachLearnWeb.Business;
using TeachLearnWeb.Data.POCOs.TeachLearnWeb;
using TeachLearnWeb.Filters;
using TeachLearnWeb.FormData.ForumController;
using TeachLearnWeb.FormData.UserProfilePhoto;

namespace TeachLearnWeb.Controllers
{
    public class ForumController : BaseController
    {
        IRepository<ForumDepartment> forumDepartmentRepository = _uow.GetRepository<ForumDepartment>();
        IRepository<ForumFaculty> forumFacultyRepository = _uow.GetRepository<ForumFaculty>();
        IRepository<Post> postRepository = _uow.GetRepository<Post>();
        IRepository<Topic> topicRepository = _uow.GetRepository<Topic>();
        IRepository<User> userRepository = _uow.GetRepository<User>();
        IRepository<SentFeeds> sentfeedsRepository = _uow.GetRepository<SentFeeds>();
        IRepository<FavouriteFeeds> favouriteFeedsRepository = _uow.GetRepository<FavouriteFeeds>();

        #region Read
        public async Task<ActionResult> Index()
        {
            ForumDepartmentIDCNT = 0;

            ForumIndexFormData fifd = new ForumIndexFormData();
            fifd.ForumDepartments = await forumDepartmentRepository.GetAllAsync();
            fifd.ForumFaculties = await forumFacultyRepository.GetAllAsync();

            return View(fifd);
        }

        public async Task<PartialViewResult> FormDepartmentsPartialInitial(int ID, int page) //partial view ı 
        {
            ForumFaculty forumFaculty = await forumFacultyRepository.GetByIdAsync(ID);


            if (forumFaculty.ForumDepartments.Count == 0)
            {
                var topicList = forumFaculty.Topics.Count >= 25 ? forumFaculty.Topics.ToList().GetRange(25 * page, 25) : forumFaculty.Topics.ToList().GetRange(25 * page, forumFaculty.Topics.Count);

                return PartialView("", topicList);
            }
            else
            {
                var topicList = forumFaculty.ForumDepartments.Count >= 25 ? forumFaculty.ForumDepartments.ToList().GetRange(25 * page, 25) : forumFaculty.ForumDepartments.ToList().GetRange(25 * page, forumFaculty.ForumDepartments.Count);
                return PartialView("", topicList);
            }



        }

        [HttpPost]
        public async Task<JsonResult> GetForumDepartments(int ID)
        {
            ForumFaculty selectedForumFaculty = await forumFacultyRepository.GetByIdAsync(ID);

            return Json(new SelectList(selectedForumFaculty.ForumDepartments.AsEnumerable(), "ID", "Name"));
        }

        public async Task<ActionResult> ForumDepartmentTopics(int ID, int? page)//default olarak 15 topic olsun her page de
        {
            ForumDepartmentIDCNT = ID;

            int _page = page == null ? 0 : (int)page;

            int fdID = (int)ID;
            ForumDepartment fd = await forumDepartmentRepository.GetByIdAsync(fdID);

            TempData["Page"] = _page;

            return View(fd);
        }

        public async Task<ActionResult> ForumFacultyDeps(int ID, int? page) //forum faculty
        {
            ForumDepartmentIDCNT = 0;

            ForumFaculty ff = await forumFacultyRepository.GetByIdAsync(ID);

            int _page = page == null ? 0 : ((int)page - 1);

            int fdID = (int)ID;

            TempData["Page"] = _page;

            return View(ff);
        }

        public async Task<ActionResult> TopicPosts(int ID, int? page, int? anchoredPostID)
        {
            Topic topic = await topicRepository.GetByIdAsync(ID);
            ICollection<ProfilePhotoFormData> ppfdList = new List<ProfilePhotoFormData>();

            int _page = page == null ? 0 : ((int)page) - 1;

            int fdID = (int)ID;

            TempData["Page"] = _page;

            if (anchoredPostID != null)
            {
                TempData["anchoredPostID"] = (int)anchoredPostID;

                Post anchoredPost = topic.Posts.SingleOrDefault(w => w.ID == anchoredPostID);

                _page = topic.Posts.IndexOf(anchoredPost) % 15 == 0 ? topic.Posts.IndexOf(anchoredPost) / 15 : (topic.Posts.IndexOf(anchoredPost) / 15);
                TempData["Page"] = _page;

            }
            if (topic.Posts != null)
            {
                foreach (var item in topic.Posts)
                {
                    if (ppfdList.SingleOrDefault(w => w.ID == item.SentFeed.User.ID) == null)
                    {
                        ProfilePhotoFormData ppfd = new ProfilePhotoFormData();
                        ppfd.ID = item.SentFeed.User.ID;
                        ppfd.Base64Image = "data:image/png;base64," + Convert.ToBase64String(item.SentFeed.User.ProfilePhoto);
                        ppfdList.Add(ppfd);
                    }
                }
            }
            TopicPageFormData tpfd = new TopicPageFormData();
            tpfd.Topic = topic;
            tpfd.ProfilePhotoFormDatas = ppfdList;
            return View(tpfd);
        }

        [UserAuthorizationFilter]
        public ActionResult SentPostList()
        {
            User currentUser = (Session["Student"] as Student).User;

            return View(currentUser.SentFeeds.SentPosts);
        }

        [UserAuthorizationFilter]
        public ActionResult SentTopicList()
        {
            User currentUser = (Session["Student"] as Student).User;
            return View(currentUser.SentFeeds.SentTopics);
        }

        [UserAuthorizationFilter]
        public ActionResult FavTopicList()
        {
            User currentUser = (Session["Student"] as Student).User;
            return View(currentUser.FavouriteFeeds.FavouriteTopics);
        }

        [UserAuthorizationFilter]
        public ActionResult FavPostList()
        {
            User currentUser = (Session["Student"] as Student).User;
            return View(currentUser.FavouriteFeeds.FavouritePosts);
        }

        #endregion

        #region Create
        [UserAuthorizationFilter]
        public async Task<ActionResult> CreateNewTopic()
        {

            if (ForumDepartmentIDCNT == 0)
            {
                TempData["ForumFaculties"] = (await forumFacultyRepository.GetAllAsync()).Select(s => new SelectListItem
                {
                    Selected = true,
                    Text = s.Name,
                    Value = s.ID.ToString()
                }).ToList();

            }
            else
            {
                ForumDepartment fd = await forumDepartmentRepository.GetByIdAsync(ForumDepartmentIDCNT);

                TempData["ForumDepartment"] = fd;
                TempData["ForumFaculty"] = fd.ForumFaculty;
            }

            return View();
        }

        [HttpPost]
        public async Task<ActionResult> CreateNewTopic(CreateNewTopicFormData cntfd)
        {
            User currentUser = (Session["Student"] as Student).User;
            ForumFaculty currentForumFaculty = await forumFacultyRepository.GetByIdAsync(cntfd.ForumFacultyID);

            ForumDepartment currentForumDepartment = await forumDepartmentRepository.GetByIdAsync(cntfd.ForumDepartmentID);

            await userRepository.AttachAsync(currentUser);
            await forumFacultyRepository.AttachAsync(currentForumFaculty);
            await forumDepartmentRepository.AttachAsync(currentForumDepartment);


            SentFeeds sf = null;

            if (currentUser.SentFeeds == null)
            {
                sf = new SentFeeds();
                sf.User = currentUser;
                currentUser.SentFeeds = sf;
                await sentfeedsRepository.AddAsync(sf);
            }
            else
            {
                sf = currentUser.SentFeeds;
            }

            Topic topic = new Topic();
            topic.Name = cntfd.TopicName;

            topic.SentFeed = sf;
            sf.SentTopics.Add(topic);

            topic.ForumFaculty = currentForumFaculty;
            currentForumFaculty.Topics.Add(topic);

            Post post = new Post();
            post.Content = cntfd.Content;
            post.PostDate = DateTime.Now;

            post.Topic = topic;
            topic.Posts.Add(post);

            post.ForumFaculty = currentForumFaculty;
            currentForumFaculty.Posts.Add(post);

            post.SentFeed = sf;
            sf.SentPosts.Add(post);


            topic.ForumDepartment = currentForumDepartment;
            currentForumDepartment.Topics.Add(topic);


            post.ForumDepartment = currentForumDepartment;
            currentForumDepartment.Posts.Add(post);


            await topicRepository.AddAsync(topic);
            await postRepository.AddAsync(post);

            ForumDepartmentIDCNT = 0;

            try
            {
                await _uow.SaveChanges();
            }
            catch (Exception ex)
            {

            }


            var redirectUrl = new UrlHelper(Request.RequestContext).Action("Index");
            return Json(new { Url = redirectUrl });

        }

        [HttpPost]
        public async Task<ActionResult> SendPost(int topicID, string postContent)
        {
            Topic currentTopic = await topicRepository.GetByIdAsync(topicID);
            User currentUser = (Session["Student"] as Student).User;

            await topicRepository.AttachAsync(currentTopic);
            await userRepository.AttachAsync(currentUser);

            SentFeeds sf = null;

            if (currentUser.SentFeeds == null)
            {
                sf = new SentFeeds();
                sf.User = currentUser;
                currentUser.SentFeeds = sf;
                await sentfeedsRepository.AddAsync(sf);
            }
            else
            {
                sf = currentUser.SentFeeds;
            }

            Post newPost = new Post();
            newPost.Topic = currentTopic;
            newPost.PostDate = DateTime.Now;

TeachLearnWeb/Views/Forum/EditPostPartial.cshtml
<input type="hidden" value="@TempData["PostID"]" id="idArea"/>
<textarea id="postUpdateTextArea" style="min-width:73%;min-height:220px;resize:none" class="form-control">@TempData["Content"]</textarea>
<br />
<div class="btn btn-default" id="btnUpdate">Update</div>
<div class="btn btn-danger" id="btnCancel">Cancel</div>

<script>
    $(function () {
        $('#btnUpdate').click(function () {
            var postContent=$('#postUpdateTextArea').val();
            var postID=$('#idArea').val();

            $.ajax({
                method: "POST",
                url:'../UpdatePost',
                type:'json',
                data: {ID:postID,content:postContent},
                success: function () {
                    window.location.reload();
                }, error: function () {
                    window.location.reload();
                }

            });
        });

        $('#btnCancel').click(function () {
            window.location.reload();

        });

    });
    
</script>

TeachLearnWeb/Views/Forum/FavPostList.cshtml
@model IEnumerable<TeachLearnWeb.Data.POCOs.TeachLearnWeb.Post>
@{
    ViewBag.Title = "FavPostList";
    Layout = "~/Views/Forum/_ForumSharedLayout.cshtml";
}

<link href="~/Content/educationdetail-css.css" rel="stylesheet" />

<div class="container">
    <div class="row">
        <div class="col-xs-12">
            <div class="invoice-title">
                <h2>Favourite Posts</h2>
            </div>
            <hr>
        </div>
        @foreach (var post in Model)
            {
            <a href=@Url.Action("TopicPosts","Forum",new { ID=post.TopicID, anchoredPostID = post.ID})>
                <div class="row">
                    <div class="col-xs-12">
                        <div class="panel panel-default">
                            <div class="panel-heading">
                                <h3 class="panel-title">
                                    <strong>@post.Topic.Name</strong>
                                </h3>
                            </div>
                            <div class="panel-body">
                                <div class="table-responsive">
                                    <table class="table table-condensed">
                                        <tbody>
                                            <tr>
                                                <td>@Html.Raw(post.Content)</td>
                                            </tr>
                                            <tr>
                                                @post.PostDate
                                            </tr>
                                        </tbody>
                                    </table>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
            </a>
            <br />
        }
    </div>
</div>

TeachLearnWeb/Views/Forum/FavTopicList.cshtml
@model IEnumerable<TeachLearnWeb.Data.POCOs.TeachLearnWeb.Topic>
@{
    ViewBag.Title = "FavTopicList";
    Layout = "~/Views/Forum/_ForumSharedLayout.cshtml";
}
<link href="~/Content/educationdetail-css.css" rel="stylesheet" />
<h2>FavTopicList</h2>

<div class="container">
    <div class="row">
        <div class="col-xs-12">
            <div class="invoice-title">
                <h2>Sent Posts</h2>
            </div>
            <hr>
        </div>
        @foreach (var topic in Model)
            {
            <a href='@Url.Action("TopicPosts","Forum",new { ID=topic.ID})'>
                <div class="row">
                    <div class="col-xs-12">
                        <div class="panel panel-default">
                            <div class="panel-heading">
                                <h3 class="panel-title">
                                    <strong>@topic.Name</strong> <div class="pull-right">@topic.Posts.OrderBy(o => o.PostDate).FirstOrDefault().PostDate</div>
                                </h3>
                                @*@Ajax.ActionLink("Delete This Lesson", "DeleteLesson", "Student", new { _scoreID = item.ID }, new AjaxOptions { HttpMethod = "POST", Confirm = "Are you sure you want to delete this lesson?", OnSuccess = "(function(){window.location.reload();})" }, new { @class = "btn btn-danger" }) &emsp;&emsp; @Html.ActionLink("Edit This Lesson", "EditLesson", "Student", new { _lessonID = item.LessonID }) &emsp;&emsp;@Html.ActionLink("Add New Note", "AddNote", "Student", new { _scoreID = item.ID }, null) &emsp;&emsp; @Html.ActionLink("Edit Notes", "EditScore", "Student", new { _scoreID = item.ID }, null)*@
                            </div>
                            <div class="panel-body">
                                <div class="table-responsive">
                                    <table class="table table-condensed">
                                        <thead>
                                            <tr>
                                                <td><strong>POST COUNT</strong></td>
                                                <td><strong>LAST POST</strong></td>
                                            </tr>
                                        </thead>
                                        <tbody>
                                            <tr>
                                                <td>@topic.Posts.Count</td>

                                                <td>
                                                    @topic.Posts.OrderByDescending(o => o.PostDate).FirstOrDefault().PostDate - @topic.Posts.OrderByDescending(o => o.PostDate).FirstOrDefault().SentFeed.User.Username
                                                </td>
                                            </tr>
                                        </tbody>
                                    </table>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
            </a>
            <br />
        }
    </div>
</div>

TeachLearnWeb/Views/Forum/ForumFacultyDeps.cshtml
@model TeachLearnWeb.Data.POCOs.TeachLearnWeb.ForumFaculty

@{
    ViewBag.Title = "ForumFacultyDeps";
    Layout = "~/Views/Forum/_ForumSharedLayout.cshtml";
    int page = 0;
    page = int.Parse(TempData["Page"].ToString());
    string lastPostString = "--";
}

<h2>@Model.Name</h2>

<div class="row">
    @foreach (var department in Model.ForumDepartments.ToList().GetRange(page * 15, Model.ForumDepartments.Count < (15 * (page + 1)) ? Model.ForumDepartments.Count % 15 : 15))
    {
        <div class="col-sm-12">
            <div class="list-group">
                <a href=@Url.Action("ForumDepartmentTopics",new { ID=department.ID}) class="list-group-item">
                    <div class="row">
                        <div class="col-sm-9">
                            @department.Name
                        </div>

                        <div class="col-sm-1">
                            <div style="border-left: 1px solid">
                                &ensp; POSTS <br />&emsp;&emsp;
                                @department.Posts.Count
                            </div>
                        </div>

                        <div class="col-sm-2">
                            <div style="border-left: 1px solid">
                                &ensp; LAST POST <br />&emsp;&emsp;
                                @if (department.Posts.OrderBy(o => o.PostDate).FirstOrDefault() != null && department.Posts.OrderBy(o => o.PostDate).FirstOrDefault().SentFeed==null)
                                {
                                    lastPostString = department.Posts.OrderBy(o => o.PostDate).FirstOrDefault().SentFeed.User.Username + " - " + department.Posts.OrderBy(o => o.PostDate).FirstOrDefault().PostDate.ToShortDateString();
                                }
        @lastPostString
    </div>
                        </div>
                    </div>
                </a>
            </div>
        </div>
    }

    <div align="center">
        <nav aria-label="Page navigation">
            <ul class="pagination">
                <li>
                    <a href='@Url.Action("ForumFacultyDeps",new { ID=Model.ID,page=(page==0 ? 0:page-1)})' aria-label="Previous">
                        <span aria-hidden="true">&laquo;</span>
                    </a>
                </li>
                @if (Model.Topics.Count / 15 == 0)
                {
                    <li><a href="#">1</a></li>
                }

                @if (Model.Topics.Count / 15 > 0)
                {
                    for (int i = 1; i <= Model.Topics.Count / 15; i++)
                    {
                        <li>@Html.ActionLink(i.ToString(), "ForumFacultyDeps", "Forum", new { ID = Model.ID, page = i }, null)</li>
                    }
                }
                <li>
                    <a href='@Url.Action("ForumFacultyDeps",new { ID=Model.ID,page=(page==0 ? 0:page+1)})' aria-label="Next">
                        <span aria-hidden="true">&raquo;</span>
                    </a>
                </li>
            </ul>
        </nav>
    </div>
</div>

TeachLearnWeb/Views/Forum/SentPostList.cshtml
@model IEnumerable<TeachLearnWeb.Data.POCOs.TeachLearnWeb.Post>
@{
    ViewBag.Title = "SentPostList";
    Layout = "~/Views/Forum/_ForumSharedLayout.cshtml";
}


<link href="~/Content/educationdetail-css.css" rel="stylesheet" />

<h2>SentPostList</h2>


<div class="container">
    <div class="row">
        <div class="col-xs-12">
            <div class="invoice-title">
                <h2>Sent Posts</h2>
            </div>
            <hr>
        </div>
        @foreach (var post in Model)
            {
            <a href=@Url.Action("TopicPosts","Forum",new { ID=post.TopicID, anchoredPostID =post.ID})>
                <div class="row">
                    <div class="col-xs-12">
                        <div class="panel panel-default">
                            <div class="panel-heading">
                                <h3 class="panel-title">
                                    <strong>@post.Topic.Name</strong>
                                </h3>
                            </div>
                            <div class="panel-body">
                                <div class="table-responsive">
                                    <table class="table table-condensed">
                                        <tbody>
                                            <tr>
                                                <td>@Html.Raw(post.Content)</td>
                                            </tr>
                                            <tr>
                                                @post.PostDate
                                            </tr>
                                        </tbody>
                                    </table>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
            </a>
                <br />
            }
        </div>
    </div>

TeachLearnWeb/Views/Forum/SentTopicList.cshtml
@model IEnumerable<TeachLearnWeb.Data.POCOs.TeachLearnWeb.Topic>

@{
    ViewBag.Title = "SentTopicList";
    Layout = "~/Views/Forum/_ForumSharedLayout.cshtml";
}
<link href="~/Content/educationdetail-css.css" rel="stylesheet" />

<h2>SentTopicList</h2>

<div class="container">
    <div class="row">
        <div class="col-xs-12">
            <div class="invoice-title">
                <h2>Sent Posts</h2>
            </div>
            <hr>
        </div>
        @foreach (var topic in Model)
            {
            <a href='@Url.Action("TopicPosts","Forum",new { ID=topic.ID})'>
                <div class="row">
                    <div class="col-xs-12">
                        <div class="panel panel-default">
                            <div class="panel-heading">
                                <h3 class="panel-title">
                                    <strong>@topic.Name</strong> <div class="pull-right">@topic.Posts.OrderBy(o => o.PostDate).FirstOrDefault().PostDate</div>
                                </h3>
                                @*@Ajax.ActionLink("Delete This Lesson", "DeleteLesson", "Student", new { _scoreID = item.ID }, new AjaxOptions { HttpMethod = "POST", Confirm = "Are you sure you want to delete this lesson?", OnSuccess = "(function(){window.location.reload();})" }, new { @class = "btn btn-danger" }) &emsp;&emsp; @Html.ActionLink("Edit This Lesson", "EditLesson", "Student", new { _lessonID = item.LessonID }) &emsp;&emsp;@Html.ActionLink("Add New Note", "AddNote", "Student", new { _scoreID = item.ID }, null) &emsp;&emsp; @Html.ActionLink("Edit Notes", "EditScore", "Student", new { _scoreID = item.ID }, null)*@
                            </div>
                            <div class="panel-body">
                                <div class="table-responsive">
                                    <table class="table table-condensed">
                                        <thead>
                                            <tr>
                                                <td><strong>POST COUNT</strong></td>
                                                <td><strong>LAST POST</strong></td>
                                            </tr>
                                        </thead>
                                        <tbody>
                                            <tr>
                                                <td>@topic.Posts.Count</td>

                                                <td>
                                                    @topic.Posts.OrderByDescending(o => o.PostDate).FirstOrDefault().PostDate - @topic.Posts.OrderByDescending(o => o.PostDate).FirstOrDefault().SentFeed.User.Username
                                                </td>
                                            </tr>
                                        </tbody>
                                    </table>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
            </a>
                <br />
        }
    </div>
</div>

TeachLearnWeb/Views/Forum/_ForumSharedLayout.cshtml
@{
    ViewBag.Title = "Live Campus Forum";
    Layout = "../Shared/_Layout.cshtml";
    int topicCount = 0;
    int postCount = 0;

    int favTopicCount = 0;
    int favPostCount = 0;


    if (Session["Student"] != null)
    {

        if ((Session["Student"] as TeachLearnWeb.Data.POCOs.TeachLearnWeb.Student).User.SentFeeds != null)
        {
            topicCount = (Session["Student"] as TeachLearnWeb.Data.POCOs.TeachLearnWeb.Student).User.SentFeeds.SentTopics.Count;
            postCount = (Session["Student"] as TeachLearnWeb.Data.POCOs.TeachLearnWeb.Student).User.SentFeeds.SentPosts.Count;
        }
        if ((Session["Student"] as TeachLearnWeb.Data.POCOs.TeachLearnWeb.Student).User.FavouriteFeeds != null)
        {
            favTopicCount = (Session["Student"] as TeachLearnWeb.Data.POCOs.TeachLearnWeb.Student).User.FavouriteFeeds.FavouriteTopics.Count;
            favPostCount = (Session["Student"] as TeachLearnWeb.Data.POCOs.TeachLearnWeb.Student).User.FavouriteFeeds.FavouritePosts.Count;
        }
    }
}

@*<h2>_ForumSharedLayout</h2>*@


<html>
<head>

</head>
<body>
    <br />
    <div class="row">
        <div class="col-sm-12">
            <div class="panel panel-default">
                <a href=@Url.Action("Index", "Forum") style="text-decoration:none;">
                    <div class="panel-body">
                        <div align="center">
                            <img class="img-rounded" src="~/images/LiveCampusLogo.png" /><br />
                            <h1><font face="Georgia" color="red">LIVE CAMPUS FORUMS</font></h1>
                        </div>
                    </div>
                </a>
            </div>
        </div>
    </div>
    <br />
    <div class="row">
        <div class="col-sm-12">
            <div class="panel panel-danger">
                <div class="panel-body">

                    <div class="col-sm-2">
                        <a href=@Url.Action("CreateNewTopic", "Forum") class="btn btn-danger">
                            <div align="left">
                                <b><font face="Georgia">New Topic</font></b>
                            </div>
                        </a>
                    </div>




                    <div class="col-sm-2">
                        <div align="center" style="border-left: 2px solid rgb(0, 0, 0)">
                            &ensp;
                            <a href=@Url.Action("SentTopicList", "Forum") class="btn btn-primary">
                                <div align="center">
                                    <b><font face="Georgia">Your Topics</font>&ensp;<span class="badge">@topicCount </span></b>
                                </div>
                            </a>
                        </div>
                    </div>


                    <div class="col-sm-2">
                        <a href=@Url.Action("SentPostList", "Forum") class="btn btn-primary">
                            <div align="center">
                                <b><font face="Georgia">Your Posts</font>&ensp;<span class="badge">@postCount </span></b>
                            </div>
                        </a>
                    </div>


                    <div class="col-sm-3">
                        <div style="border-left: 2px solid rgb(0, 0, 0)">
                            &ensp;
                            <a href=@Url.Action("FavTopicList", "Forum") class="btn btn-success">
                                <div align="center">
                                    <b><font face="Georgia">Your Favourite Topics</font>&ensp;<span class="badge">@favTopicCount </span></b>
                                </div>
                            </a>
                        </div>
                    </div>

                    <div class="col-sm-3">
                        <a href=@Url.Action("FavPostList", "Forum") class="btn btn-success">
                            <div align="right">
                                <b><font face="Georgia">Your Favourite Posts</font>&ensp;<span class="badge">@favPostCount </span></b>
                            </div>
                        </a>
                    </div>

                </div>
            </div>
        </div>
    </div>
    <hr />
    <br />
    @RenderBody()
</body>
</html>